return {
	require("plugins.tree-sitter-manager"),
	require("plugins.gitsigns"),
	require("plugins.which_keys"),
	require("plugins.telescope"),
	require("plugins.nvim-lspconfig"),
	require("plugins.conform"),
	require("plugins.theme"),
	require("plugins.mini"),
	require("plugins.blink_cmp"),
	-- require("plugins.blink_indent"),
	require("plugins.blink_pairs"),
	require("plugins.venv-selector"),
	require("plugins.todo-comment"),
	require("plugins.trouble"),
	require("plugins.tiny-inline-diagnostic"),
}
